### PR TITLE
Fix for error "Source and destination path must have identical roots. Move will not work across volumes"

### LINKED ISSUE #145: Directory.Move doesn't work on different volumes
Sorry for the brief description, but this is easy to understand:

After the commit from pull request #135, a mechanism was implemented to support concurrency, by atomically moving the temporary directory to the destination. Problem is, **Directory.Move()** doesn't work if the source and target directories are on different volumes.

As a workaround, I'm changing the TMP environment variable to a directory in the same volume, to avoid the problem.

To solve this bug without losing concurrency support, you can just put the staging directory on the same folder as the target, instead of using GetTempPath.

### PR DESCRIPTION
**Pull request by FermJacob**
Closes #145 

Fix for error "Source and destination path must have identical roots. Move will not work across volumes"

https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.move?redirectedfrom=MSDN&view=net-5.0#exceptions

### CODE REVIEW

File: WebDriverManager/Services/Impl/BinaryService.cs [hunk 1]
```diff
@@ -85,7 +84,16 @@ public string SetupBinary(string url, string zipPath, string binaryPath)
             Exception renameException = null;
             try
             {
-                Directory.Move(stagingDir, binaryDir);
+                string[] files = Directory.GetFiles(stagingDir);
+
+                // Copy the files and overwrite destination files if they already exist.
+                foreach (string s in files)
```
Comment (rosolko) [inline WebDriverManager/Services/Impl/BinaryService.cs:90]:
```suggestion
                foreach (string file in files)
```

**Review by rosolko — CHANGES_REQUESTED** [review]
One single note

File: WebDriverManager/Services/Impl/BinaryService.cs (hunk 1 above)
Comment (FermJacob) [reply WebDriverManager/Services/Impl/BinaryService.cs]: @rosolko Done.

**Comment by vkudley** [comment]
It will help to have new NuGet pushed. 
As of now we have to roll back to 2.11.3 to keep library working.
